/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CreateBackendAPIRequestResourceConfigConflictResolution;
import org.openapitools.client.model.CreateBackendAPIRequestResourceConfigDefaultAuthType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BackendAPIResourceConfig
 */
public class BackendAPIResourceConfigTest {
    private final BackendAPIResourceConfig model = new BackendAPIResourceConfig();

    /**
     * Model tests for BackendAPIResourceConfig
     */
    @Test
    public void testBackendAPIResourceConfig() {
        // TODO: test BackendAPIResourceConfig
    }

    /**
     * Test the property 'additionalAuthTypes'
     */
    @Test
    public void additionalAuthTypesTest() {
        // TODO: test additionalAuthTypes
    }

    /**
     * Test the property 'apiName'
     */
    @Test
    public void apiNameTest() {
        // TODO: test apiName
    }

    /**
     * Test the property 'conflictResolution'
     */
    @Test
    public void conflictResolutionTest() {
        // TODO: test conflictResolution
    }

    /**
     * Test the property 'defaultAuthType'
     */
    @Test
    public void defaultAuthTypeTest() {
        // TODO: test defaultAuthType
    }

    /**
     * Test the property 'service'
     */
    @Test
    public void serviceTest() {
        // TODO: test service
    }

    /**
     * Test the property 'transformSchema'
     */
    @Test
    public void transformSchemaTest() {
        // TODO: test transformSchema
    }

}
