/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CloneBackendRequest
 */
public class CloneBackendRequestTest {
    private final CloneBackendRequest model = new CloneBackendRequest();

    /**
     * Model tests for CloneBackendRequest
     */
    @Test
    public void testCloneBackendRequest() {
        // TODO: test CloneBackendRequest
    }

    /**
     * Test the property 'targetEnvironmentName'
     */
    @Test
    public void targetEnvironmentNameTest() {
        // TODO: test targetEnvironmentName
    }

}
