/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CreateBackendAuthRequestResourceConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateBackendAuthRequest
 */
public class CreateBackendAuthRequestTest {
    private final CreateBackendAuthRequest model = new CreateBackendAuthRequest();

    /**
     * Model tests for CreateBackendAuthRequest
     */
    @Test
    public void testCreateBackendAuthRequest() {
        // TODO: test CreateBackendAuthRequest
    }

    /**
     * Test the property 'backendEnvironmentName'
     */
    @Test
    public void backendEnvironmentNameTest() {
        // TODO: test backendEnvironmentName
    }

    /**
     * Test the property 'resourceConfig'
     */
    @Test
    public void resourceConfigTest() {
        // TODO: test resourceConfig
    }

    /**
     * Test the property 'resourceName'
     */
    @Test
    public void resourceNameTest() {
        // TODO: test resourceName
    }

}
