/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AuthResources;
import org.openapitools.client.model.CreateBackendAuthRequestResourceConfigIdentityPoolConfigs;
import org.openapitools.client.model.CreateBackendAuthRequestResourceConfigUserPoolConfigs;
import org.openapitools.client.model.Service;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetBackendAuthResponseResourceConfig
 */
public class GetBackendAuthResponseResourceConfigTest {
    private final GetBackendAuthResponseResourceConfig model = new GetBackendAuthResponseResourceConfig();

    /**
     * Model tests for GetBackendAuthResponseResourceConfig
     */
    @Test
    public void testGetBackendAuthResponseResourceConfig() {
        // TODO: test GetBackendAuthResponseResourceConfig
    }

    /**
     * Test the property 'authResources'
     */
    @Test
    public void authResourcesTest() {
        // TODO: test authResources
    }

    /**
     * Test the property 'identityPoolConfigs'
     */
    @Test
    public void identityPoolConfigsTest() {
        // TODO: test identityPoolConfigs
    }

    /**
     * Test the property 'service'
     */
    @Test
    public void serviceTest() {
        // TODO: test service
    }

    /**
     * Test the property 'userPoolConfigs'
     */
    @Test
    public void userPoolConfigsTest() {
        // TODO: test userPoolConfigs
    }

}
