/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Status;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetBackendAPIModelsResponse
 */
public class GetBackendAPIModelsResponseTest {
    private final GetBackendAPIModelsResponse model = new GetBackendAPIModelsResponse();

    /**
     * Model tests for GetBackendAPIModelsResponse
     */
    @Test
    public void testGetBackendAPIModelsResponse() {
        // TODO: test GetBackendAPIModelsResponse
    }

    /**
     * Test the property 'models'
     */
    @Test
    public void modelsTest() {
        // TODO: test models
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'modelIntrospectionSchema'
     */
    @Test
    public void modelIntrospectionSchemaTest() {
        // TODO: test modelIntrospectionSchema
    }

}
