/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ImportBackendAuthRequest
 */
public class ImportBackendAuthRequestTest {
    private final ImportBackendAuthRequest model = new ImportBackendAuthRequest();

    /**
     * Model tests for ImportBackendAuthRequest
     */
    @Test
    public void testImportBackendAuthRequest() {
        // TODO: test ImportBackendAuthRequest
    }

    /**
     * Test the property 'identityPoolId'
     */
    @Test
    public void identityPoolIdTest() {
        // TODO: test identityPoolId
    }

    /**
     * Test the property 'nativeClientId'
     */
    @Test
    public void nativeClientIdTest() {
        // TODO: test nativeClientId
    }

    /**
     * Test the property 'userPoolId'
     */
    @Test
    public void userPoolIdTest() {
        // TODO: test userPoolId
    }

    /**
     * Test the property 'webClientId'
     */
    @Test
    public void webClientIdTest() {
        // TODO: test webClientId
    }

}
