/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LoginAuthConfigReqObj
 */
public class LoginAuthConfigReqObjTest {
    private final LoginAuthConfigReqObj model = new LoginAuthConfigReqObj();

    /**
     * Model tests for LoginAuthConfigReqObj
     */
    @Test
    public void testLoginAuthConfigReqObj() {
        // TODO: test LoginAuthConfigReqObj
    }

    /**
     * Test the property 'awsCognitoIdentityPoolId'
     */
    @Test
    public void awsCognitoIdentityPoolIdTest() {
        // TODO: test awsCognitoIdentityPoolId
    }

    /**
     * Test the property 'awsCognitoRegion'
     */
    @Test
    public void awsCognitoRegionTest() {
        // TODO: test awsCognitoRegion
    }

    /**
     * Test the property 'awsUserPoolsId'
     */
    @Test
    public void awsUserPoolsIdTest() {
        // TODO: test awsUserPoolsId
    }

    /**
     * Test the property 'awsUserPoolsWebClientId'
     */
    @Test
    public void awsUserPoolsWebClientIdTest() {
        // TODO: test awsUserPoolsWebClientId
    }

}
