/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RemoveAllBackendsRequest
 */
public class RemoveAllBackendsRequestTest {
    private final RemoveAllBackendsRequest model = new RemoveAllBackendsRequest();

    /**
     * Model tests for RemoveAllBackendsRequest
     */
    @Test
    public void testRemoveAllBackendsRequest() {
        // TODO: test RemoveAllBackendsRequest
    }

    /**
     * Test the property 'cleanAmplifyApp'
     */
    @Test
    public void cleanAmplifyAppTest() {
        // TODO: test cleanAmplifyApp
    }

}
