/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Settings
 */
public class SettingsTest {
    private final Settings model = new Settings();

    /**
     * Model tests for Settings
     */
    @Test
    public void testSettings() {
        // TODO: test Settings
    }

    /**
     * Test the property 'mfaTypes'
     */
    @Test
    public void mfaTypesTest() {
        // TODO: test mfaTypes
    }

    /**
     * Test the property 'smsMessage'
     */
    @Test
    public void smsMessageTest() {
        // TODO: test smsMessage
    }

}
