/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.UpdateBackendAuthUserPoolConfigForgotPassword;
import org.openapitools.client.model.UpdateBackendAuthUserPoolConfigMfa;
import org.openapitools.client.model.UpdateBackendAuthUserPoolConfigOAuth;
import org.openapitools.client.model.UpdateBackendAuthUserPoolConfigPasswordPolicy;
import org.openapitools.client.model.UpdateBackendAuthUserPoolConfigVerificationMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateBackendAuthRequestResourceConfigUserPoolConfigs
 */
public class UpdateBackendAuthRequestResourceConfigUserPoolConfigsTest {
    private final UpdateBackendAuthRequestResourceConfigUserPoolConfigs model = new UpdateBackendAuthRequestResourceConfigUserPoolConfigs();

    /**
     * Model tests for UpdateBackendAuthRequestResourceConfigUserPoolConfigs
     */
    @Test
    public void testUpdateBackendAuthRequestResourceConfigUserPoolConfigs() {
        // TODO: test UpdateBackendAuthRequestResourceConfigUserPoolConfigs
    }

    /**
     * Test the property 'forgotPassword'
     */
    @Test
    public void forgotPasswordTest() {
        // TODO: test forgotPassword
    }

    /**
     * Test the property 'mfa'
     */
    @Test
    public void mfaTest() {
        // TODO: test mfa
    }

    /**
     * Test the property 'oauth'
     */
    @Test
    public void oauthTest() {
        // TODO: test oauth
    }

    /**
     * Test the property 'passwordPolicy'
     */
    @Test
    public void passwordPolicyTest() {
        // TODO: test passwordPolicy
    }

    /**
     * Test the property 'verificationMessage'
     */
    @Test
    public void verificationMessageTest() {
        // TODO: test verificationMessage
    }

}
