/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.BackendAuthAppleProviderConfig;
import org.openapitools.client.model.BackendAuthSocialProviderConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateBackendAuthOAuthConfigSocialProviderSettings
 */
public class UpdateBackendAuthOAuthConfigSocialProviderSettingsTest {
    private final UpdateBackendAuthOAuthConfigSocialProviderSettings model = new UpdateBackendAuthOAuthConfigSocialProviderSettings();

    /**
     * Model tests for UpdateBackendAuthOAuthConfigSocialProviderSettings
     */
    @Test
    public void testUpdateBackendAuthOAuthConfigSocialProviderSettings() {
        // TODO: test UpdateBackendAuthOAuthConfigSocialProviderSettings
    }

    /**
     * Test the property 'facebook'
     */
    @Test
    public void facebookTest() {
        // TODO: test facebook
    }

    /**
     * Test the property 'google'
     */
    @Test
    public void googleTest() {
        // TODO: test google
    }

    /**
     * Test the property 'loginWithAmazon'
     */
    @Test
    public void loginWithAmazonTest() {
        // TODO: test loginWithAmazon
    }

    /**
     * Test the property 'signInWithApple'
     */
    @Test
    public void signInWithAppleTest() {
        // TODO: test signInWithApple
    }

}
