/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.UpdateBackendConfigRequestLoginAuthConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateBackendConfigRequest
 */
public class UpdateBackendConfigRequestTest {
    private final UpdateBackendConfigRequest model = new UpdateBackendConfigRequest();

    /**
     * Model tests for UpdateBackendConfigRequest
     */
    @Test
    public void testUpdateBackendConfigRequest() {
        // TODO: test UpdateBackendConfigRequest
    }

    /**
     * Test the property 'loginAuthConfig'
     */
    @Test
    public void loginAuthConfigTest() {
        // TODO: test loginAuthConfig
    }

}
