/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.UpdateBackendConfigResponseLoginAuthConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateBackendConfigResponse
 */
public class UpdateBackendConfigResponseTest {
    private final UpdateBackendConfigResponse model = new UpdateBackendConfigResponse();

    /**
     * Model tests for UpdateBackendConfigResponse
     */
    @Test
    public void testUpdateBackendConfigResponse() {
        // TODO: test UpdateBackendConfigResponse
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'backendManagerAppId'
     */
    @Test
    public void backendManagerAppIdTest() {
        // TODO: test backendManagerAppId
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'loginAuthConfig'
     */
    @Test
    public void loginAuthConfigTest() {
        // TODO: test loginAuthConfig
    }

}
