/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.OAuthGrantType;
import org.openapitools.client.model.UpdateBackendAuthOAuthConfigSocialProviderSettings;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateBackendAuthUserPoolConfigOAuth
 */
public class UpdateBackendAuthUserPoolConfigOAuthTest {
    private final UpdateBackendAuthUserPoolConfigOAuth model = new UpdateBackendAuthUserPoolConfigOAuth();

    /**
     * Model tests for UpdateBackendAuthUserPoolConfigOAuth
     */
    @Test
    public void testUpdateBackendAuthUserPoolConfigOAuth() {
        // TODO: test UpdateBackendAuthUserPoolConfigOAuth
    }

    /**
     * Test the property 'domainPrefix'
     */
    @Test
    public void domainPrefixTest() {
        // TODO: test domainPrefix
    }

    /**
     * Test the property 'oauthGrantType'
     */
    @Test
    public void oauthGrantTypeTest() {
        // TODO: test oauthGrantType
    }

    /**
     * Test the property 'oauthScopes'
     */
    @Test
    public void oauthScopesTest() {
        // TODO: test oauthScopes
    }

    /**
     * Test the property 'redirectSignInURIs'
     */
    @Test
    public void redirectSignInURIsTest() {
        // TODO: test redirectSignInURIs
    }

    /**
     * Test the property 'redirectSignOutURIs'
     */
    @Test
    public void redirectSignOutURIsTest() {
        // TODO: test redirectSignOutURIs
    }

    /**
     * Test the property 'socialProviderSettings'
     */
    @Test
    public void socialProviderSettingsTest() {
        // TODO: test socialProviderSettings
    }

}
