/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Describes Apple social federation configurations for allowing your app users to sign in using OAuth.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class BackendAuthAppleProviderConfig {
  public static final String SERIALIZED_NAME_CLIENT_ID = "ClientId";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  @javax.annotation.Nullable
  private String clientId;

  public static final String SERIALIZED_NAME_KEY_ID = "KeyId";
  @SerializedName(SERIALIZED_NAME_KEY_ID)
  @javax.annotation.Nullable
  private String keyId;

  public static final String SERIALIZED_NAME_PRIVATE_KEY = "PrivateKey";
  @SerializedName(SERIALIZED_NAME_PRIVATE_KEY)
  @javax.annotation.Nullable
  private String privateKey;

  public static final String SERIALIZED_NAME_TEAM_ID = "TeamId";
  @SerializedName(SERIALIZED_NAME_TEAM_ID)
  @javax.annotation.Nullable
  private String teamId;

  public BackendAuthAppleProviderConfig() {
  }

  public BackendAuthAppleProviderConfig clientId(@javax.annotation.Nullable String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Get clientId
   * @return clientId
   */
  @javax.annotation.Nullable
  public String getClientId() {
    return clientId;
  }

  public void setClientId(@javax.annotation.Nullable String clientId) {
    this.clientId = clientId;
  }


  public BackendAuthAppleProviderConfig keyId(@javax.annotation.Nullable String keyId) {
    this.keyId = keyId;
    return this;
  }

  /**
   * Get keyId
   * @return keyId
   */
  @javax.annotation.Nullable
  public String getKeyId() {
    return keyId;
  }

  public void setKeyId(@javax.annotation.Nullable String keyId) {
    this.keyId = keyId;
  }


  public BackendAuthAppleProviderConfig privateKey(@javax.annotation.Nullable String privateKey) {
    this.privateKey = privateKey;
    return this;
  }

  /**
   * Get privateKey
   * @return privateKey
   */
  @javax.annotation.Nullable
  public String getPrivateKey() {
    return privateKey;
  }

  public void setPrivateKey(@javax.annotation.Nullable String privateKey) {
    this.privateKey = privateKey;
  }


  public BackendAuthAppleProviderConfig teamId(@javax.annotation.Nullable String teamId) {
    this.teamId = teamId;
    return this;
  }

  /**
   * Get teamId
   * @return teamId
   */
  @javax.annotation.Nullable
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(@javax.annotation.Nullable String teamId) {
    this.teamId = teamId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackendAuthAppleProviderConfig backendAuthAppleProviderConfig = (BackendAuthAppleProviderConfig) o;
    return Objects.equals(this.clientId, backendAuthAppleProviderConfig.clientId) &&
        Objects.equals(this.keyId, backendAuthAppleProviderConfig.keyId) &&
        Objects.equals(this.privateKey, backendAuthAppleProviderConfig.privateKey) &&
        Objects.equals(this.teamId, backendAuthAppleProviderConfig.teamId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, keyId, privateKey, teamId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackendAuthAppleProviderConfig {\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
    sb.append("    privateKey: ").append(toIndentedString(privateKey)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ClientId");
    openapiFields.add("KeyId");
    openapiFields.add("PrivateKey");
    openapiFields.add("TeamId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BackendAuthAppleProviderConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BackendAuthAppleProviderConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BackendAuthAppleProviderConfig is not found in the empty JSON string", BackendAuthAppleProviderConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BackendAuthAppleProviderConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BackendAuthAppleProviderConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `ClientId`
      if (jsonObj.get("ClientId") != null && !jsonObj.get("ClientId").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ClientId"));
      }
      // validate the optional field `KeyId`
      if (jsonObj.get("KeyId") != null && !jsonObj.get("KeyId").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("KeyId"));
      }
      // validate the optional field `PrivateKey`
      if (jsonObj.get("PrivateKey") != null && !jsonObj.get("PrivateKey").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("PrivateKey"));
      }
      // validate the optional field `TeamId`
      if (jsonObj.get("TeamId") != null && !jsonObj.get("TeamId").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("TeamId"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BackendAuthAppleProviderConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BackendAuthAppleProviderConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BackendAuthAppleProviderConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BackendAuthAppleProviderConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<BackendAuthAppleProviderConfig>() {
           @Override
           public void write(JsonWriter out, BackendAuthAppleProviderConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BackendAuthAppleProviderConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BackendAuthAppleProviderConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BackendAuthAppleProviderConfig
   * @throws IOException if the JSON string is invalid with respect to BackendAuthAppleProviderConfig
   */
  public static BackendAuthAppleProviderConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BackendAuthAppleProviderConfig.class);
  }

  /**
   * Convert an instance of BackendAuthAppleProviderConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

