/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * The authentication settings for accessing provisioned data models in your Amplify project.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class BackendAPIAppSyncAuthSettings {
  public static final String SERIALIZED_NAME_COGNITO_USER_POOL_ID = "CognitoUserPoolId";
  @SerializedName(SERIALIZED_NAME_COGNITO_USER_POOL_ID)
  @javax.annotation.Nullable
  private String cognitoUserPoolId;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_EXPIRATION_TIME = "ExpirationTime";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_TIME)
  @javax.annotation.Nullable
  private Double expirationTime;

  public static final String SERIALIZED_NAME_OPEN_I_D_AUTH_T_T_L = "OpenIDAuthTTL";
  @SerializedName(SERIALIZED_NAME_OPEN_I_D_AUTH_T_T_L)
  @javax.annotation.Nullable
  private String openIDAuthTTL;

  public static final String SERIALIZED_NAME_OPEN_I_D_CLIENT_ID = "OpenIDClientId";
  @SerializedName(SERIALIZED_NAME_OPEN_I_D_CLIENT_ID)
  @javax.annotation.Nullable
  private String openIDClientId;

  public static final String SERIALIZED_NAME_OPEN_I_D_IAT_T_T_L = "OpenIDIatTTL";
  @SerializedName(SERIALIZED_NAME_OPEN_I_D_IAT_T_T_L)
  @javax.annotation.Nullable
  private String openIDIatTTL;

  public static final String SERIALIZED_NAME_OPEN_I_D_ISSUE_U_R_L = "OpenIDIssueURL";
  @SerializedName(SERIALIZED_NAME_OPEN_I_D_ISSUE_U_R_L)
  @javax.annotation.Nullable
  private String openIDIssueURL;

  public static final String SERIALIZED_NAME_OPEN_I_D_PROVIDER_NAME = "OpenIDProviderName";
  @SerializedName(SERIALIZED_NAME_OPEN_I_D_PROVIDER_NAME)
  @javax.annotation.Nullable
  private String openIDProviderName;

  public BackendAPIAppSyncAuthSettings() {
  }

  public BackendAPIAppSyncAuthSettings cognitoUserPoolId(@javax.annotation.Nullable String cognitoUserPoolId) {
    this.cognitoUserPoolId = cognitoUserPoolId;
    return this;
  }

  /**
   * Get cognitoUserPoolId
   * @return cognitoUserPoolId
   */
  @javax.annotation.Nullable
  public String getCognitoUserPoolId() {
    return cognitoUserPoolId;
  }

  public void setCognitoUserPoolId(@javax.annotation.Nullable String cognitoUserPoolId) {
    this.cognitoUserPoolId = cognitoUserPoolId;
  }


  public BackendAPIAppSyncAuthSettings description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public BackendAPIAppSyncAuthSettings expirationTime(@javax.annotation.Nullable Double expirationTime) {
    this.expirationTime = expirationTime;
    return this;
  }

  /**
   * Get expirationTime
   * @return expirationTime
   */
  @javax.annotation.Nullable
  public Double getExpirationTime() {
    return expirationTime;
  }

  public void setExpirationTime(@javax.annotation.Nullable Double expirationTime) {
    this.expirationTime = expirationTime;
  }


  public BackendAPIAppSyncAuthSettings openIDAuthTTL(@javax.annotation.Nullable String openIDAuthTTL) {
    this.openIDAuthTTL = openIDAuthTTL;
    return this;
  }

  /**
   * Get openIDAuthTTL
   * @return openIDAuthTTL
   */
  @javax.annotation.Nullable
  public String getOpenIDAuthTTL() {
    return openIDAuthTTL;
  }

  public void setOpenIDAuthTTL(@javax.annotation.Nullable String openIDAuthTTL) {
    this.openIDAuthTTL = openIDAuthTTL;
  }


  public BackendAPIAppSyncAuthSettings openIDClientId(@javax.annotation.Nullable String openIDClientId) {
    this.openIDClientId = openIDClientId;
    return this;
  }

  /**
   * Get openIDClientId
   * @return openIDClientId
   */
  @javax.annotation.Nullable
  public String getOpenIDClientId() {
    return openIDClientId;
  }

  public void setOpenIDClientId(@javax.annotation.Nullable String openIDClientId) {
    this.openIDClientId = openIDClientId;
  }


  public BackendAPIAppSyncAuthSettings openIDIatTTL(@javax.annotation.Nullable String openIDIatTTL) {
    this.openIDIatTTL = openIDIatTTL;
    return this;
  }

  /**
   * Get openIDIatTTL
   * @return openIDIatTTL
   */
  @javax.annotation.Nullable
  public String getOpenIDIatTTL() {
    return openIDIatTTL;
  }

  public void setOpenIDIatTTL(@javax.annotation.Nullable String openIDIatTTL) {
    this.openIDIatTTL = openIDIatTTL;
  }


  public BackendAPIAppSyncAuthSettings openIDIssueURL(@javax.annotation.Nullable String openIDIssueURL) {
    this.openIDIssueURL = openIDIssueURL;
    return this;
  }

  /**
   * Get openIDIssueURL
   * @return openIDIssueURL
   */
  @javax.annotation.Nullable
  public String getOpenIDIssueURL() {
    return openIDIssueURL;
  }

  public void setOpenIDIssueURL(@javax.annotation.Nullable String openIDIssueURL) {
    this.openIDIssueURL = openIDIssueURL;
  }


  public BackendAPIAppSyncAuthSettings openIDProviderName(@javax.annotation.Nullable String openIDProviderName) {
    this.openIDProviderName = openIDProviderName;
    return this;
  }

  /**
   * Get openIDProviderName
   * @return openIDProviderName
   */
  @javax.annotation.Nullable
  public String getOpenIDProviderName() {
    return openIDProviderName;
  }

  public void setOpenIDProviderName(@javax.annotation.Nullable String openIDProviderName) {
    this.openIDProviderName = openIDProviderName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackendAPIAppSyncAuthSettings backendAPIAppSyncAuthSettings = (BackendAPIAppSyncAuthSettings) o;
    return Objects.equals(this.cognitoUserPoolId, backendAPIAppSyncAuthSettings.cognitoUserPoolId) &&
        Objects.equals(this.description, backendAPIAppSyncAuthSettings.description) &&
        Objects.equals(this.expirationTime, backendAPIAppSyncAuthSettings.expirationTime) &&
        Objects.equals(this.openIDAuthTTL, backendAPIAppSyncAuthSettings.openIDAuthTTL) &&
        Objects.equals(this.openIDClientId, backendAPIAppSyncAuthSettings.openIDClientId) &&
        Objects.equals(this.openIDIatTTL, backendAPIAppSyncAuthSettings.openIDIatTTL) &&
        Objects.equals(this.openIDIssueURL, backendAPIAppSyncAuthSettings.openIDIssueURL) &&
        Objects.equals(this.openIDProviderName, backendAPIAppSyncAuthSettings.openIDProviderName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cognitoUserPoolId, description, expirationTime, openIDAuthTTL, openIDClientId, openIDIatTTL, openIDIssueURL, openIDProviderName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackendAPIAppSyncAuthSettings {\n");
    sb.append("    cognitoUserPoolId: ").append(toIndentedString(cognitoUserPoolId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expirationTime: ").append(toIndentedString(expirationTime)).append("\n");
    sb.append("    openIDAuthTTL: ").append(toIndentedString(openIDAuthTTL)).append("\n");
    sb.append("    openIDClientId: ").append(toIndentedString(openIDClientId)).append("\n");
    sb.append("    openIDIatTTL: ").append(toIndentedString(openIDIatTTL)).append("\n");
    sb.append("    openIDIssueURL: ").append(toIndentedString(openIDIssueURL)).append("\n");
    sb.append("    openIDProviderName: ").append(toIndentedString(openIDProviderName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CognitoUserPoolId");
    openapiFields.add("Description");
    openapiFields.add("ExpirationTime");
    openapiFields.add("OpenIDAuthTTL");
    openapiFields.add("OpenIDClientId");
    openapiFields.add("OpenIDIatTTL");
    openapiFields.add("OpenIDIssueURL");
    openapiFields.add("OpenIDProviderName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BackendAPIAppSyncAuthSettings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BackendAPIAppSyncAuthSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BackendAPIAppSyncAuthSettings is not found in the empty JSON string", BackendAPIAppSyncAuthSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BackendAPIAppSyncAuthSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BackendAPIAppSyncAuthSettings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `CognitoUserPoolId`
      if (jsonObj.get("CognitoUserPoolId") != null && !jsonObj.get("CognitoUserPoolId").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("CognitoUserPoolId"));
      }
      // validate the optional field `Description`
      if (jsonObj.get("Description") != null && !jsonObj.get("Description").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Description"));
      }
      // validate the optional field `ExpirationTime`
      if (jsonObj.get("ExpirationTime") != null && !jsonObj.get("ExpirationTime").isJsonNull()) {
        Double.validateJsonElement(jsonObj.get("ExpirationTime"));
      }
      // validate the optional field `OpenIDAuthTTL`
      if (jsonObj.get("OpenIDAuthTTL") != null && !jsonObj.get("OpenIDAuthTTL").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("OpenIDAuthTTL"));
      }
      // validate the optional field `OpenIDClientId`
      if (jsonObj.get("OpenIDClientId") != null && !jsonObj.get("OpenIDClientId").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("OpenIDClientId"));
      }
      // validate the optional field `OpenIDIatTTL`
      if (jsonObj.get("OpenIDIatTTL") != null && !jsonObj.get("OpenIDIatTTL").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("OpenIDIatTTL"));
      }
      // validate the optional field `OpenIDIssueURL`
      if (jsonObj.get("OpenIDIssueURL") != null && !jsonObj.get("OpenIDIssueURL").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("OpenIDIssueURL"));
      }
      // validate the optional field `OpenIDProviderName`
      if (jsonObj.get("OpenIDProviderName") != null && !jsonObj.get("OpenIDProviderName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("OpenIDProviderName"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BackendAPIAppSyncAuthSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BackendAPIAppSyncAuthSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BackendAPIAppSyncAuthSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BackendAPIAppSyncAuthSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<BackendAPIAppSyncAuthSettings>() {
           @Override
           public void write(JsonWriter out, BackendAPIAppSyncAuthSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BackendAPIAppSyncAuthSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BackendAPIAppSyncAuthSettings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BackendAPIAppSyncAuthSettings
   * @throws IOException if the JSON string is invalid with respect to BackendAPIAppSyncAuthSettings
   */
  public static BackendAPIAppSyncAuthSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BackendAPIAppSyncAuthSettings.class);
  }

  /**
   * Convert an instance of BackendAPIAppSyncAuthSettings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

