/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateBackendAuthMFAConfigSettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateBackendAuthMFAConfigSettings {
  public static final String SERIALIZED_NAME_MFA_TYPES = "MfaTypes";
  @SerializedName(SERIALIZED_NAME_MFA_TYPES)
  @javax.annotation.Nullable
  private List mfaTypes;

  public static final String SERIALIZED_NAME_SMS_MESSAGE = "SmsMessage";
  @SerializedName(SERIALIZED_NAME_SMS_MESSAGE)
  @javax.annotation.Nullable
  private String smsMessage;

  public CreateBackendAuthMFAConfigSettings() {
  }

  public CreateBackendAuthMFAConfigSettings mfaTypes(@javax.annotation.Nullable List mfaTypes) {
    this.mfaTypes = mfaTypes;
    return this;
  }

  /**
   * Get mfaTypes
   * @return mfaTypes
   */
  @javax.annotation.Nullable
  public List getMfaTypes() {
    return mfaTypes;
  }

  public void setMfaTypes(@javax.annotation.Nullable List mfaTypes) {
    this.mfaTypes = mfaTypes;
  }


  public CreateBackendAuthMFAConfigSettings smsMessage(@javax.annotation.Nullable String smsMessage) {
    this.smsMessage = smsMessage;
    return this;
  }

  /**
   * Get smsMessage
   * @return smsMessage
   */
  @javax.annotation.Nullable
  public String getSmsMessage() {
    return smsMessage;
  }

  public void setSmsMessage(@javax.annotation.Nullable String smsMessage) {
    this.smsMessage = smsMessage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBackendAuthMFAConfigSettings createBackendAuthMFAConfigSettings = (CreateBackendAuthMFAConfigSettings) o;
    return Objects.equals(this.mfaTypes, createBackendAuthMFAConfigSettings.mfaTypes) &&
        Objects.equals(this.smsMessage, createBackendAuthMFAConfigSettings.smsMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mfaTypes, smsMessage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBackendAuthMFAConfigSettings {\n");
    sb.append("    mfaTypes: ").append(toIndentedString(mfaTypes)).append("\n");
    sb.append("    smsMessage: ").append(toIndentedString(smsMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MfaTypes");
    openapiFields.add("SmsMessage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateBackendAuthMFAConfigSettings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateBackendAuthMFAConfigSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateBackendAuthMFAConfigSettings is not found in the empty JSON string", CreateBackendAuthMFAConfigSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateBackendAuthMFAConfigSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateBackendAuthMFAConfigSettings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `MfaTypes`
      if (jsonObj.get("MfaTypes") != null && !jsonObj.get("MfaTypes").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("MfaTypes"));
      }
      // validate the optional field `SmsMessage`
      if (jsonObj.get("SmsMessage") != null && !jsonObj.get("SmsMessage").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("SmsMessage"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateBackendAuthMFAConfigSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateBackendAuthMFAConfigSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateBackendAuthMFAConfigSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateBackendAuthMFAConfigSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateBackendAuthMFAConfigSettings>() {
           @Override
           public void write(JsonWriter out, CreateBackendAuthMFAConfigSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateBackendAuthMFAConfigSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateBackendAuthMFAConfigSettings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateBackendAuthMFAConfigSettings
   * @throws IOException if the JSON string is invalid with respect to CreateBackendAuthMFAConfigSettings
   */
  public static CreateBackendAuthMFAConfigSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateBackendAuthMFAConfigSettings.class);
  }

  /**
   * Convert an instance of CreateBackendAuthMFAConfigSettings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

