/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateBackendRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateBackendRequest {
  public static final String SERIALIZED_NAME_APP_ID = "appId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  @javax.annotation.Nonnull
  private String appId;

  public static final String SERIALIZED_NAME_APP_NAME = "appName";
  @SerializedName(SERIALIZED_NAME_APP_NAME)
  @javax.annotation.Nonnull
  private String appName;

  public static final String SERIALIZED_NAME_BACKEND_ENVIRONMENT_NAME = "backendEnvironmentName";
  @SerializedName(SERIALIZED_NAME_BACKEND_ENVIRONMENT_NAME)
  @javax.annotation.Nonnull
  private String backendEnvironmentName;

  public static final String SERIALIZED_NAME_RESOURCE_CONFIG = "resourceConfig";
  @SerializedName(SERIALIZED_NAME_RESOURCE_CONFIG)
  @javax.annotation.Nullable
  private Object resourceConfig;

  public static final String SERIALIZED_NAME_RESOURCE_NAME = "resourceName";
  @SerializedName(SERIALIZED_NAME_RESOURCE_NAME)
  @javax.annotation.Nullable
  private String resourceName;

  public CreateBackendRequest() {
  }

  public CreateBackendRequest appId(@javax.annotation.Nonnull String appId) {
    this.appId = appId;
    return this;
  }

  /**
   * The app ID.
   * @return appId
   */
  @javax.annotation.Nonnull
  public String getAppId() {
    return appId;
  }

  public void setAppId(@javax.annotation.Nonnull String appId) {
    this.appId = appId;
  }


  public CreateBackendRequest appName(@javax.annotation.Nonnull String appName) {
    this.appName = appName;
    return this;
  }

  /**
   * The name of the app.
   * @return appName
   */
  @javax.annotation.Nonnull
  public String getAppName() {
    return appName;
  }

  public void setAppName(@javax.annotation.Nonnull String appName) {
    this.appName = appName;
  }


  public CreateBackendRequest backendEnvironmentName(@javax.annotation.Nonnull String backendEnvironmentName) {
    this.backendEnvironmentName = backendEnvironmentName;
    return this;
  }

  /**
   * The name of the backend environment.
   * @return backendEnvironmentName
   */
  @javax.annotation.Nonnull
  public String getBackendEnvironmentName() {
    return backendEnvironmentName;
  }

  public void setBackendEnvironmentName(@javax.annotation.Nonnull String backendEnvironmentName) {
    this.backendEnvironmentName = backendEnvironmentName;
  }


  public CreateBackendRequest resourceConfig(@javax.annotation.Nullable Object resourceConfig) {
    this.resourceConfig = resourceConfig;
    return this;
  }

  /**
   * Defines the resource configuration for the data model in your Amplify project.
   * @return resourceConfig
   */
  @javax.annotation.Nullable
  public Object getResourceConfig() {
    return resourceConfig;
  }

  public void setResourceConfig(@javax.annotation.Nullable Object resourceConfig) {
    this.resourceConfig = resourceConfig;
  }


  public CreateBackendRequest resourceName(@javax.annotation.Nullable String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

  /**
   * The name of the resource.
   * @return resourceName
   */
  @javax.annotation.Nullable
  public String getResourceName() {
    return resourceName;
  }

  public void setResourceName(@javax.annotation.Nullable String resourceName) {
    this.resourceName = resourceName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBackendRequest createBackendRequest = (CreateBackendRequest) o;
    return Objects.equals(this.appId, createBackendRequest.appId) &&
        Objects.equals(this.appName, createBackendRequest.appName) &&
        Objects.equals(this.backendEnvironmentName, createBackendRequest.backendEnvironmentName) &&
        Objects.equals(this.resourceConfig, createBackendRequest.resourceConfig) &&
        Objects.equals(this.resourceName, createBackendRequest.resourceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, appName, backendEnvironmentName, resourceConfig, resourceName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBackendRequest {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    appName: ").append(toIndentedString(appName)).append("\n");
    sb.append("    backendEnvironmentName: ").append(toIndentedString(backendEnvironmentName)).append("\n");
    sb.append("    resourceConfig: ").append(toIndentedString(resourceConfig)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("appId");
    openapiFields.add("appName");
    openapiFields.add("backendEnvironmentName");
    openapiFields.add("resourceConfig");
    openapiFields.add("resourceName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("appId");
    openapiRequiredFields.add("appName");
    openapiRequiredFields.add("backendEnvironmentName");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateBackendRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateBackendRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateBackendRequest is not found in the empty JSON string", CreateBackendRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateBackendRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateBackendRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateBackendRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("appId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `appId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("appId").toString()));
      }
      if (!jsonObj.get("appName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `appName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("appName").toString()));
      }
      if (!jsonObj.get("backendEnvironmentName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `backendEnvironmentName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("backendEnvironmentName").toString()));
      }
      if ((jsonObj.get("resourceName") != null && !jsonObj.get("resourceName").isJsonNull()) && !jsonObj.get("resourceName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resourceName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resourceName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateBackendRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateBackendRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateBackendRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateBackendRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateBackendRequest>() {
           @Override
           public void write(JsonWriter out, CreateBackendRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateBackendRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateBackendRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateBackendRequest
   * @throws IOException if the JSON string is invalid with respect to CreateBackendRequest
   */
  public static CreateBackendRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateBackendRequest.class);
  }

  /**
   * Convert an instance of CreateBackendRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

