/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * The password policy configuration for the backend to your Amplify project.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateBackendAuthPasswordPolicyConfig {
  public static final String SERIALIZED_NAME_ADDITIONAL_CONSTRAINTS = "AdditionalConstraints";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_CONSTRAINTS)
  @javax.annotation.Nullable
  private List additionalConstraints;

  public static final String SERIALIZED_NAME_MINIMUM_LENGTH = "MinimumLength";
  @SerializedName(SERIALIZED_NAME_MINIMUM_LENGTH)
  @javax.annotation.Nonnull
  private Double minimumLength;

  public CreateBackendAuthPasswordPolicyConfig() {
  }

  public CreateBackendAuthPasswordPolicyConfig additionalConstraints(@javax.annotation.Nullable List additionalConstraints) {
    this.additionalConstraints = additionalConstraints;
    return this;
  }

  /**
   * Get additionalConstraints
   * @return additionalConstraints
   */
  @javax.annotation.Nullable
  public List getAdditionalConstraints() {
    return additionalConstraints;
  }

  public void setAdditionalConstraints(@javax.annotation.Nullable List additionalConstraints) {
    this.additionalConstraints = additionalConstraints;
  }


  public CreateBackendAuthPasswordPolicyConfig minimumLength(@javax.annotation.Nonnull Double minimumLength) {
    this.minimumLength = minimumLength;
    return this;
  }

  /**
   * Get minimumLength
   * @return minimumLength
   */
  @javax.annotation.Nonnull
  public Double getMinimumLength() {
    return minimumLength;
  }

  public void setMinimumLength(@javax.annotation.Nonnull Double minimumLength) {
    this.minimumLength = minimumLength;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBackendAuthPasswordPolicyConfig createBackendAuthPasswordPolicyConfig = (CreateBackendAuthPasswordPolicyConfig) o;
    return Objects.equals(this.additionalConstraints, createBackendAuthPasswordPolicyConfig.additionalConstraints) &&
        Objects.equals(this.minimumLength, createBackendAuthPasswordPolicyConfig.minimumLength);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalConstraints, minimumLength);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBackendAuthPasswordPolicyConfig {\n");
    sb.append("    additionalConstraints: ").append(toIndentedString(additionalConstraints)).append("\n");
    sb.append("    minimumLength: ").append(toIndentedString(minimumLength)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AdditionalConstraints");
    openapiFields.add("MinimumLength");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("MinimumLength");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateBackendAuthPasswordPolicyConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateBackendAuthPasswordPolicyConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateBackendAuthPasswordPolicyConfig is not found in the empty JSON string", CreateBackendAuthPasswordPolicyConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateBackendAuthPasswordPolicyConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateBackendAuthPasswordPolicyConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateBackendAuthPasswordPolicyConfig.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `AdditionalConstraints`
      if (jsonObj.get("AdditionalConstraints") != null && !jsonObj.get("AdditionalConstraints").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("AdditionalConstraints"));
      }
      // validate the required field `MinimumLength`
      Double.validateJsonElement(jsonObj.get("MinimumLength"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateBackendAuthPasswordPolicyConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateBackendAuthPasswordPolicyConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateBackendAuthPasswordPolicyConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateBackendAuthPasswordPolicyConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateBackendAuthPasswordPolicyConfig>() {
           @Override
           public void write(JsonWriter out, CreateBackendAuthPasswordPolicyConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateBackendAuthPasswordPolicyConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateBackendAuthPasswordPolicyConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateBackendAuthPasswordPolicyConfig
   * @throws IOException if the JSON string is invalid with respect to CreateBackendAuthPasswordPolicyConfig
   */
  public static CreateBackendAuthPasswordPolicyConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateBackendAuthPasswordPolicyConfig.class);
  }

  /**
   * Convert an instance of CreateBackendAuthPasswordPolicyConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

