/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateBackendAuthVerificationMessageConfigEmailSettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateBackendAuthVerificationMessageConfigEmailSettings {
  public static final String SERIALIZED_NAME_EMAIL_MESSAGE = "EmailMessage";
  @SerializedName(SERIALIZED_NAME_EMAIL_MESSAGE)
  @javax.annotation.Nullable
  private String emailMessage;

  public static final String SERIALIZED_NAME_EMAIL_SUBJECT = "EmailSubject";
  @SerializedName(SERIALIZED_NAME_EMAIL_SUBJECT)
  @javax.annotation.Nullable
  private String emailSubject;

  public CreateBackendAuthVerificationMessageConfigEmailSettings() {
  }

  public CreateBackendAuthVerificationMessageConfigEmailSettings emailMessage(@javax.annotation.Nullable String emailMessage) {
    this.emailMessage = emailMessage;
    return this;
  }

  /**
   * Get emailMessage
   * @return emailMessage
   */
  @javax.annotation.Nullable
  public String getEmailMessage() {
    return emailMessage;
  }

  public void setEmailMessage(@javax.annotation.Nullable String emailMessage) {
    this.emailMessage = emailMessage;
  }


  public CreateBackendAuthVerificationMessageConfigEmailSettings emailSubject(@javax.annotation.Nullable String emailSubject) {
    this.emailSubject = emailSubject;
    return this;
  }

  /**
   * Get emailSubject
   * @return emailSubject
   */
  @javax.annotation.Nullable
  public String getEmailSubject() {
    return emailSubject;
  }

  public void setEmailSubject(@javax.annotation.Nullable String emailSubject) {
    this.emailSubject = emailSubject;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBackendAuthVerificationMessageConfigEmailSettings createBackendAuthVerificationMessageConfigEmailSettings = (CreateBackendAuthVerificationMessageConfigEmailSettings) o;
    return Objects.equals(this.emailMessage, createBackendAuthVerificationMessageConfigEmailSettings.emailMessage) &&
        Objects.equals(this.emailSubject, createBackendAuthVerificationMessageConfigEmailSettings.emailSubject);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailMessage, emailSubject);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBackendAuthVerificationMessageConfigEmailSettings {\n");
    sb.append("    emailMessage: ").append(toIndentedString(emailMessage)).append("\n");
    sb.append("    emailSubject: ").append(toIndentedString(emailSubject)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("EmailMessage");
    openapiFields.add("EmailSubject");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateBackendAuthVerificationMessageConfigEmailSettings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateBackendAuthVerificationMessageConfigEmailSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateBackendAuthVerificationMessageConfigEmailSettings is not found in the empty JSON string", CreateBackendAuthVerificationMessageConfigEmailSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateBackendAuthVerificationMessageConfigEmailSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateBackendAuthVerificationMessageConfigEmailSettings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `EmailMessage`
      if (jsonObj.get("EmailMessage") != null && !jsonObj.get("EmailMessage").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("EmailMessage"));
      }
      // validate the optional field `EmailSubject`
      if (jsonObj.get("EmailSubject") != null && !jsonObj.get("EmailSubject").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("EmailSubject"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateBackendAuthVerificationMessageConfigEmailSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateBackendAuthVerificationMessageConfigEmailSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateBackendAuthVerificationMessageConfigEmailSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateBackendAuthVerificationMessageConfigEmailSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateBackendAuthVerificationMessageConfigEmailSettings>() {
           @Override
           public void write(JsonWriter out, CreateBackendAuthVerificationMessageConfigEmailSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateBackendAuthVerificationMessageConfigEmailSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateBackendAuthVerificationMessageConfigEmailSettings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateBackendAuthVerificationMessageConfigEmailSettings
   * @throws IOException if the JSON string is invalid with respect to CreateBackendAuthVerificationMessageConfigEmailSettings
   */
  public static CreateBackendAuthVerificationMessageConfigEmailSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateBackendAuthVerificationMessageConfigEmailSettings.class);
  }

  /**
   * Convert an instance of CreateBackendAuthVerificationMessageConfigEmailSettings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

