/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateTokenResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateTokenResponse {
  public static final String SERIALIZED_NAME_APP_ID = "AppId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  @javax.annotation.Nullable
  private String appId;

  public static final String SERIALIZED_NAME_CHALLENGE_CODE = "ChallengeCode";
  @SerializedName(SERIALIZED_NAME_CHALLENGE_CODE)
  @javax.annotation.Nullable
  private String challengeCode;

  public static final String SERIALIZED_NAME_SESSION_ID = "SessionId";
  @SerializedName(SERIALIZED_NAME_SESSION_ID)
  @javax.annotation.Nullable
  private String sessionId;

  public static final String SERIALIZED_NAME_TTL = "Ttl";
  @SerializedName(SERIALIZED_NAME_TTL)
  @javax.annotation.Nullable
  private String ttl;

  public CreateTokenResponse() {
  }

  public CreateTokenResponse appId(@javax.annotation.Nullable String appId) {
    this.appId = appId;
    return this;
  }

  /**
   * Get appId
   * @return appId
   */
  @javax.annotation.Nullable
  public String getAppId() {
    return appId;
  }

  public void setAppId(@javax.annotation.Nullable String appId) {
    this.appId = appId;
  }


  public CreateTokenResponse challengeCode(@javax.annotation.Nullable String challengeCode) {
    this.challengeCode = challengeCode;
    return this;
  }

  /**
   * Get challengeCode
   * @return challengeCode
   */
  @javax.annotation.Nullable
  public String getChallengeCode() {
    return challengeCode;
  }

  public void setChallengeCode(@javax.annotation.Nullable String challengeCode) {
    this.challengeCode = challengeCode;
  }


  public CreateTokenResponse sessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

  /**
   * Get sessionId
   * @return sessionId
   */
  @javax.annotation.Nullable
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
  }


  public CreateTokenResponse ttl(@javax.annotation.Nullable String ttl) {
    this.ttl = ttl;
    return this;
  }

  /**
   * Get ttl
   * @return ttl
   */
  @javax.annotation.Nullable
  public String getTtl() {
    return ttl;
  }

  public void setTtl(@javax.annotation.Nullable String ttl) {
    this.ttl = ttl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTokenResponse createTokenResponse = (CreateTokenResponse) o;
    return Objects.equals(this.appId, createTokenResponse.appId) &&
        Objects.equals(this.challengeCode, createTokenResponse.challengeCode) &&
        Objects.equals(this.sessionId, createTokenResponse.sessionId) &&
        Objects.equals(this.ttl, createTokenResponse.ttl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, challengeCode, sessionId, ttl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTokenResponse {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    challengeCode: ").append(toIndentedString(challengeCode)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    ttl: ").append(toIndentedString(ttl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AppId");
    openapiFields.add("ChallengeCode");
    openapiFields.add("SessionId");
    openapiFields.add("Ttl");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateTokenResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateTokenResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateTokenResponse is not found in the empty JSON string", CreateTokenResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateTokenResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateTokenResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `AppId`
      if (jsonObj.get("AppId") != null && !jsonObj.get("AppId").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("AppId"));
      }
      // validate the optional field `ChallengeCode`
      if (jsonObj.get("ChallengeCode") != null && !jsonObj.get("ChallengeCode").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ChallengeCode"));
      }
      // validate the optional field `SessionId`
      if (jsonObj.get("SessionId") != null && !jsonObj.get("SessionId").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("SessionId"));
      }
      // validate the optional field `Ttl`
      if (jsonObj.get("Ttl") != null && !jsonObj.get("Ttl").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Ttl"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateTokenResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateTokenResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateTokenResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateTokenResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateTokenResponse>() {
           @Override
           public void write(JsonWriter out, CreateTokenResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateTokenResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateTokenResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateTokenResponse
   * @throws IOException if the JSON string is invalid with respect to CreateTokenResponse
   */
  public static CreateTokenResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateTokenResponse.class);
  }

  /**
   * Convert an instance of CreateTokenResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

