/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateBackendAuthRequestResourceConfigIdentityPoolConfigs
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateBackendAuthRequestResourceConfigIdentityPoolConfigs {
  public static final String SERIALIZED_NAME_IDENTITY_POOL_NAME = "IdentityPoolName";
  @SerializedName(SERIALIZED_NAME_IDENTITY_POOL_NAME)
  @javax.annotation.Nonnull
  private String identityPoolName;

  public static final String SERIALIZED_NAME_UNAUTHENTICATED_LOGIN = "UnauthenticatedLogin";
  @SerializedName(SERIALIZED_NAME_UNAUTHENTICATED_LOGIN)
  @javax.annotation.Nonnull
  private Boolean unauthenticatedLogin;

  public CreateBackendAuthRequestResourceConfigIdentityPoolConfigs() {
  }

  public CreateBackendAuthRequestResourceConfigIdentityPoolConfigs identityPoolName(@javax.annotation.Nonnull String identityPoolName) {
    this.identityPoolName = identityPoolName;
    return this;
  }

  /**
   * Get identityPoolName
   * @return identityPoolName
   */
  @javax.annotation.Nonnull
  public String getIdentityPoolName() {
    return identityPoolName;
  }

  public void setIdentityPoolName(@javax.annotation.Nonnull String identityPoolName) {
    this.identityPoolName = identityPoolName;
  }


  public CreateBackendAuthRequestResourceConfigIdentityPoolConfigs unauthenticatedLogin(@javax.annotation.Nonnull Boolean unauthenticatedLogin) {
    this.unauthenticatedLogin = unauthenticatedLogin;
    return this;
  }

  /**
   * Get unauthenticatedLogin
   * @return unauthenticatedLogin
   */
  @javax.annotation.Nonnull
  public Boolean getUnauthenticatedLogin() {
    return unauthenticatedLogin;
  }

  public void setUnauthenticatedLogin(@javax.annotation.Nonnull Boolean unauthenticatedLogin) {
    this.unauthenticatedLogin = unauthenticatedLogin;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBackendAuthRequestResourceConfigIdentityPoolConfigs createBackendAuthRequestResourceConfigIdentityPoolConfigs = (CreateBackendAuthRequestResourceConfigIdentityPoolConfigs) o;
    return Objects.equals(this.identityPoolName, createBackendAuthRequestResourceConfigIdentityPoolConfigs.identityPoolName) &&
        Objects.equals(this.unauthenticatedLogin, createBackendAuthRequestResourceConfigIdentityPoolConfigs.unauthenticatedLogin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identityPoolName, unauthenticatedLogin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBackendAuthRequestResourceConfigIdentityPoolConfigs {\n");
    sb.append("    identityPoolName: ").append(toIndentedString(identityPoolName)).append("\n");
    sb.append("    unauthenticatedLogin: ").append(toIndentedString(unauthenticatedLogin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("IdentityPoolName");
    openapiFields.add("UnauthenticatedLogin");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("IdentityPoolName");
    openapiRequiredFields.add("UnauthenticatedLogin");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateBackendAuthRequestResourceConfigIdentityPoolConfigs
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateBackendAuthRequestResourceConfigIdentityPoolConfigs.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateBackendAuthRequestResourceConfigIdentityPoolConfigs is not found in the empty JSON string", CreateBackendAuthRequestResourceConfigIdentityPoolConfigs.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateBackendAuthRequestResourceConfigIdentityPoolConfigs.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateBackendAuthRequestResourceConfigIdentityPoolConfigs` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateBackendAuthRequestResourceConfigIdentityPoolConfigs.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `IdentityPoolName`
      String.validateJsonElement(jsonObj.get("IdentityPoolName"));
      // validate the required field `UnauthenticatedLogin`
      Boolean.validateJsonElement(jsonObj.get("UnauthenticatedLogin"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateBackendAuthRequestResourceConfigIdentityPoolConfigs.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateBackendAuthRequestResourceConfigIdentityPoolConfigs' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateBackendAuthRequestResourceConfigIdentityPoolConfigs> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateBackendAuthRequestResourceConfigIdentityPoolConfigs.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateBackendAuthRequestResourceConfigIdentityPoolConfigs>() {
           @Override
           public void write(JsonWriter out, CreateBackendAuthRequestResourceConfigIdentityPoolConfigs value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateBackendAuthRequestResourceConfigIdentityPoolConfigs read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateBackendAuthRequestResourceConfigIdentityPoolConfigs given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateBackendAuthRequestResourceConfigIdentityPoolConfigs
   * @throws IOException if the JSON string is invalid with respect to CreateBackendAuthRequestResourceConfigIdentityPoolConfigs
   */
  public static CreateBackendAuthRequestResourceConfigIdentityPoolConfigs fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateBackendAuthRequestResourceConfigIdentityPoolConfigs.class);
  }

  /**
   * Convert an instance of CreateBackendAuthRequestResourceConfigIdentityPoolConfigs to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

