/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateBackendStorageRequestResourceConfigPermissions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateBackendStorageRequestResourceConfigPermissions {
  public static final String SERIALIZED_NAME_AUTHENTICATED = "Authenticated";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATED)
  @javax.annotation.Nonnull
  private List authenticated;

  public static final String SERIALIZED_NAME_UN_AUTHENTICATED = "UnAuthenticated";
  @SerializedName(SERIALIZED_NAME_UN_AUTHENTICATED)
  @javax.annotation.Nullable
  private List unAuthenticated;

  public CreateBackendStorageRequestResourceConfigPermissions() {
  }

  public CreateBackendStorageRequestResourceConfigPermissions authenticated(@javax.annotation.Nonnull List authenticated) {
    this.authenticated = authenticated;
    return this;
  }

  /**
   * Get authenticated
   * @return authenticated
   */
  @javax.annotation.Nonnull
  public List getAuthenticated() {
    return authenticated;
  }

  public void setAuthenticated(@javax.annotation.Nonnull List authenticated) {
    this.authenticated = authenticated;
  }


  public CreateBackendStorageRequestResourceConfigPermissions unAuthenticated(@javax.annotation.Nullable List unAuthenticated) {
    this.unAuthenticated = unAuthenticated;
    return this;
  }

  /**
   * Get unAuthenticated
   * @return unAuthenticated
   */
  @javax.annotation.Nullable
  public List getUnAuthenticated() {
    return unAuthenticated;
  }

  public void setUnAuthenticated(@javax.annotation.Nullable List unAuthenticated) {
    this.unAuthenticated = unAuthenticated;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBackendStorageRequestResourceConfigPermissions createBackendStorageRequestResourceConfigPermissions = (CreateBackendStorageRequestResourceConfigPermissions) o;
    return Objects.equals(this.authenticated, createBackendStorageRequestResourceConfigPermissions.authenticated) &&
        Objects.equals(this.unAuthenticated, createBackendStorageRequestResourceConfigPermissions.unAuthenticated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticated, unAuthenticated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBackendStorageRequestResourceConfigPermissions {\n");
    sb.append("    authenticated: ").append(toIndentedString(authenticated)).append("\n");
    sb.append("    unAuthenticated: ").append(toIndentedString(unAuthenticated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Authenticated");
    openapiFields.add("UnAuthenticated");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("Authenticated");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateBackendStorageRequestResourceConfigPermissions
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateBackendStorageRequestResourceConfigPermissions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateBackendStorageRequestResourceConfigPermissions is not found in the empty JSON string", CreateBackendStorageRequestResourceConfigPermissions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateBackendStorageRequestResourceConfigPermissions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateBackendStorageRequestResourceConfigPermissions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateBackendStorageRequestResourceConfigPermissions.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `Authenticated`
      List.validateJsonElement(jsonObj.get("Authenticated"));
      // validate the optional field `UnAuthenticated`
      if (jsonObj.get("UnAuthenticated") != null && !jsonObj.get("UnAuthenticated").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("UnAuthenticated"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateBackendStorageRequestResourceConfigPermissions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateBackendStorageRequestResourceConfigPermissions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateBackendStorageRequestResourceConfigPermissions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateBackendStorageRequestResourceConfigPermissions.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateBackendStorageRequestResourceConfigPermissions>() {
           @Override
           public void write(JsonWriter out, CreateBackendStorageRequestResourceConfigPermissions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateBackendStorageRequestResourceConfigPermissions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateBackendStorageRequestResourceConfigPermissions given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateBackendStorageRequestResourceConfigPermissions
   * @throws IOException if the JSON string is invalid with respect to CreateBackendStorageRequestResourceConfigPermissions
   */
  public static CreateBackendStorageRequestResourceConfigPermissions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateBackendStorageRequestResourceConfigPermissions.class);
  }

  /**
   * Convert an instance of CreateBackendStorageRequestResourceConfigPermissions to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

