/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CreateBackendAPIRequestResourceConfig;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DeleteBackendAPIRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DeleteBackendAPIRequest {
  public static final String SERIALIZED_NAME_RESOURCE_CONFIG = "resourceConfig";
  @SerializedName(SERIALIZED_NAME_RESOURCE_CONFIG)
  @javax.annotation.Nullable
  private CreateBackendAPIRequestResourceConfig resourceConfig;

  public static final String SERIALIZED_NAME_RESOURCE_NAME = "resourceName";
  @SerializedName(SERIALIZED_NAME_RESOURCE_NAME)
  @javax.annotation.Nonnull
  private String resourceName;

  public DeleteBackendAPIRequest() {
  }

  public DeleteBackendAPIRequest resourceConfig(@javax.annotation.Nullable CreateBackendAPIRequestResourceConfig resourceConfig) {
    this.resourceConfig = resourceConfig;
    return this;
  }

  /**
   * Get resourceConfig
   * @return resourceConfig
   */
  @javax.annotation.Nullable
  public CreateBackendAPIRequestResourceConfig getResourceConfig() {
    return resourceConfig;
  }

  public void setResourceConfig(@javax.annotation.Nullable CreateBackendAPIRequestResourceConfig resourceConfig) {
    this.resourceConfig = resourceConfig;
  }


  public DeleteBackendAPIRequest resourceName(@javax.annotation.Nonnull String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

  /**
   * The name of this resource.
   * @return resourceName
   */
  @javax.annotation.Nonnull
  public String getResourceName() {
    return resourceName;
  }

  public void setResourceName(@javax.annotation.Nonnull String resourceName) {
    this.resourceName = resourceName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteBackendAPIRequest deleteBackendAPIRequest = (DeleteBackendAPIRequest) o;
    return Objects.equals(this.resourceConfig, deleteBackendAPIRequest.resourceConfig) &&
        Objects.equals(this.resourceName, deleteBackendAPIRequest.resourceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceConfig, resourceName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteBackendAPIRequest {\n");
    sb.append("    resourceConfig: ").append(toIndentedString(resourceConfig)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("resourceConfig");
    openapiFields.add("resourceName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("resourceName");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeleteBackendAPIRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeleteBackendAPIRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeleteBackendAPIRequest is not found in the empty JSON string", DeleteBackendAPIRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeleteBackendAPIRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeleteBackendAPIRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DeleteBackendAPIRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `resourceConfig`
      if (jsonObj.get("resourceConfig") != null && !jsonObj.get("resourceConfig").isJsonNull()) {
        CreateBackendAPIRequestResourceConfig.validateJsonElement(jsonObj.get("resourceConfig"));
      }
      if (!jsonObj.get("resourceName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resourceName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resourceName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeleteBackendAPIRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeleteBackendAPIRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeleteBackendAPIRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeleteBackendAPIRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DeleteBackendAPIRequest>() {
           @Override
           public void write(JsonWriter out, DeleteBackendAPIRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeleteBackendAPIRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeleteBackendAPIRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeleteBackendAPIRequest
   * @throws IOException if the JSON string is invalid with respect to DeleteBackendAPIRequest
   */
  public static DeleteBackendAPIRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeleteBackendAPIRequest.class);
  }

  /**
   * Convert an instance of DeleteBackendAPIRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

