/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Status;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetBackendAPIModelsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class GetBackendAPIModelsResponse {
  public static final String SERIALIZED_NAME_MODELS = "Models";
  @SerializedName(SERIALIZED_NAME_MODELS)
  @javax.annotation.Nullable
  private String models;

  public static final String SERIALIZED_NAME_STATUS = "Status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private Status status;

  public static final String SERIALIZED_NAME_MODEL_INTROSPECTION_SCHEMA = "ModelIntrospectionSchema";
  @SerializedName(SERIALIZED_NAME_MODEL_INTROSPECTION_SCHEMA)
  @javax.annotation.Nullable
  private String modelIntrospectionSchema;

  public GetBackendAPIModelsResponse() {
  }

  public GetBackendAPIModelsResponse models(@javax.annotation.Nullable String models) {
    this.models = models;
    return this;
  }

  /**
   * Get models
   * @return models
   */
  @javax.annotation.Nullable
  public String getModels() {
    return models;
  }

  public void setModels(@javax.annotation.Nullable String models) {
    this.models = models;
  }


  public GetBackendAPIModelsResponse status(@javax.annotation.Nullable Status status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public Status getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable Status status) {
    this.status = status;
  }


  public GetBackendAPIModelsResponse modelIntrospectionSchema(@javax.annotation.Nullable String modelIntrospectionSchema) {
    this.modelIntrospectionSchema = modelIntrospectionSchema;
    return this;
  }

  /**
   * Get modelIntrospectionSchema
   * @return modelIntrospectionSchema
   */
  @javax.annotation.Nullable
  public String getModelIntrospectionSchema() {
    return modelIntrospectionSchema;
  }

  public void setModelIntrospectionSchema(@javax.annotation.Nullable String modelIntrospectionSchema) {
    this.modelIntrospectionSchema = modelIntrospectionSchema;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetBackendAPIModelsResponse getBackendAPIModelsResponse = (GetBackendAPIModelsResponse) o;
    return Objects.equals(this.models, getBackendAPIModelsResponse.models) &&
        Objects.equals(this.status, getBackendAPIModelsResponse.status) &&
        Objects.equals(this.modelIntrospectionSchema, getBackendAPIModelsResponse.modelIntrospectionSchema);
  }

  @Override
  public int hashCode() {
    return Objects.hash(models, status, modelIntrospectionSchema);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetBackendAPIModelsResponse {\n");
    sb.append("    models: ").append(toIndentedString(models)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    modelIntrospectionSchema: ").append(toIndentedString(modelIntrospectionSchema)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Models");
    openapiFields.add("Status");
    openapiFields.add("ModelIntrospectionSchema");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetBackendAPIModelsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetBackendAPIModelsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetBackendAPIModelsResponse is not found in the empty JSON string", GetBackendAPIModelsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetBackendAPIModelsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetBackendAPIModelsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `Models`
      if (jsonObj.get("Models") != null && !jsonObj.get("Models").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Models"));
      }
      // validate the optional field `Status`
      if (jsonObj.get("Status") != null && !jsonObj.get("Status").isJsonNull()) {
        Status.validateJsonElement(jsonObj.get("Status"));
      }
      // validate the optional field `ModelIntrospectionSchema`
      if (jsonObj.get("ModelIntrospectionSchema") != null && !jsonObj.get("ModelIntrospectionSchema").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ModelIntrospectionSchema"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetBackendAPIModelsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetBackendAPIModelsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetBackendAPIModelsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetBackendAPIModelsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetBackendAPIModelsResponse>() {
           @Override
           public void write(JsonWriter out, GetBackendAPIModelsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetBackendAPIModelsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetBackendAPIModelsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetBackendAPIModelsResponse
   * @throws IOException if the JSON string is invalid with respect to GetBackendAPIModelsResponse
   */
  public static GetBackendAPIModelsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetBackendAPIModelsResponse.class);
  }

  /**
   * Convert an instance of GetBackendAPIModelsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

