/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetBackendRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class GetBackendRequest {
  public static final String SERIALIZED_NAME_BACKEND_ENVIRONMENT_NAME = "backendEnvironmentName";
  @SerializedName(SERIALIZED_NAME_BACKEND_ENVIRONMENT_NAME)
  @javax.annotation.Nullable
  private String backendEnvironmentName;

  public GetBackendRequest() {
  }

  public GetBackendRequest backendEnvironmentName(@javax.annotation.Nullable String backendEnvironmentName) {
    this.backendEnvironmentName = backendEnvironmentName;
    return this;
  }

  /**
   * The name of the backend environment.
   * @return backendEnvironmentName
   */
  @javax.annotation.Nullable
  public String getBackendEnvironmentName() {
    return backendEnvironmentName;
  }

  public void setBackendEnvironmentName(@javax.annotation.Nullable String backendEnvironmentName) {
    this.backendEnvironmentName = backendEnvironmentName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetBackendRequest getBackendRequest = (GetBackendRequest) o;
    return Objects.equals(this.backendEnvironmentName, getBackendRequest.backendEnvironmentName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backendEnvironmentName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetBackendRequest {\n");
    sb.append("    backendEnvironmentName: ").append(toIndentedString(backendEnvironmentName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("backendEnvironmentName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetBackendRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetBackendRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetBackendRequest is not found in the empty JSON string", GetBackendRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetBackendRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetBackendRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("backendEnvironmentName") != null && !jsonObj.get("backendEnvironmentName").isJsonNull()) && !jsonObj.get("backendEnvironmentName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `backendEnvironmentName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("backendEnvironmentName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetBackendRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetBackendRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetBackendRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetBackendRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<GetBackendRequest>() {
           @Override
           public void write(JsonWriter out, GetBackendRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetBackendRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetBackendRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetBackendRequest
   * @throws IOException if the JSON string is invalid with respect to GetBackendRequest
   */
  public static GetBackendRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetBackendRequest.class);
  }

  /**
   * Convert an instance of GetBackendRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

