/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GetBackendAuthResponseResourceConfig;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetBackendAuthResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class GetBackendAuthResponse {
  public static final String SERIALIZED_NAME_APP_ID = "AppId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  @javax.annotation.Nullable
  private String appId;

  public static final String SERIALIZED_NAME_BACKEND_ENVIRONMENT_NAME = "BackendEnvironmentName";
  @SerializedName(SERIALIZED_NAME_BACKEND_ENVIRONMENT_NAME)
  @javax.annotation.Nullable
  private String backendEnvironmentName;

  public static final String SERIALIZED_NAME_ERROR = "Error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  @javax.annotation.Nullable
  private String error;

  public static final String SERIALIZED_NAME_RESOURCE_CONFIG = "ResourceConfig";
  @SerializedName(SERIALIZED_NAME_RESOURCE_CONFIG)
  @javax.annotation.Nullable
  private GetBackendAuthResponseResourceConfig resourceConfig;

  public static final String SERIALIZED_NAME_RESOURCE_NAME = "ResourceName";
  @SerializedName(SERIALIZED_NAME_RESOURCE_NAME)
  @javax.annotation.Nullable
  private String resourceName;

  public GetBackendAuthResponse() {
  }

  public GetBackendAuthResponse appId(@javax.annotation.Nullable String appId) {
    this.appId = appId;
    return this;
  }

  /**
   * Get appId
   * @return appId
   */
  @javax.annotation.Nullable
  public String getAppId() {
    return appId;
  }

  public void setAppId(@javax.annotation.Nullable String appId) {
    this.appId = appId;
  }


  public GetBackendAuthResponse backendEnvironmentName(@javax.annotation.Nullable String backendEnvironmentName) {
    this.backendEnvironmentName = backendEnvironmentName;
    return this;
  }

  /**
   * Get backendEnvironmentName
   * @return backendEnvironmentName
   */
  @javax.annotation.Nullable
  public String getBackendEnvironmentName() {
    return backendEnvironmentName;
  }

  public void setBackendEnvironmentName(@javax.annotation.Nullable String backendEnvironmentName) {
    this.backendEnvironmentName = backendEnvironmentName;
  }


  public GetBackendAuthResponse error(@javax.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  public String getError() {
    return error;
  }

  public void setError(@javax.annotation.Nullable String error) {
    this.error = error;
  }


  public GetBackendAuthResponse resourceConfig(@javax.annotation.Nullable GetBackendAuthResponseResourceConfig resourceConfig) {
    this.resourceConfig = resourceConfig;
    return this;
  }

  /**
   * Get resourceConfig
   * @return resourceConfig
   */
  @javax.annotation.Nullable
  public GetBackendAuthResponseResourceConfig getResourceConfig() {
    return resourceConfig;
  }

  public void setResourceConfig(@javax.annotation.Nullable GetBackendAuthResponseResourceConfig resourceConfig) {
    this.resourceConfig = resourceConfig;
  }


  public GetBackendAuthResponse resourceName(@javax.annotation.Nullable String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

  /**
   * Get resourceName
   * @return resourceName
   */
  @javax.annotation.Nullable
  public String getResourceName() {
    return resourceName;
  }

  public void setResourceName(@javax.annotation.Nullable String resourceName) {
    this.resourceName = resourceName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetBackendAuthResponse getBackendAuthResponse = (GetBackendAuthResponse) o;
    return Objects.equals(this.appId, getBackendAuthResponse.appId) &&
        Objects.equals(this.backendEnvironmentName, getBackendAuthResponse.backendEnvironmentName) &&
        Objects.equals(this.error, getBackendAuthResponse.error) &&
        Objects.equals(this.resourceConfig, getBackendAuthResponse.resourceConfig) &&
        Objects.equals(this.resourceName, getBackendAuthResponse.resourceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, backendEnvironmentName, error, resourceConfig, resourceName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetBackendAuthResponse {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    backendEnvironmentName: ").append(toIndentedString(backendEnvironmentName)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    resourceConfig: ").append(toIndentedString(resourceConfig)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AppId");
    openapiFields.add("BackendEnvironmentName");
    openapiFields.add("Error");
    openapiFields.add("ResourceConfig");
    openapiFields.add("ResourceName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetBackendAuthResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetBackendAuthResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetBackendAuthResponse is not found in the empty JSON string", GetBackendAuthResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetBackendAuthResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetBackendAuthResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `AppId`
      if (jsonObj.get("AppId") != null && !jsonObj.get("AppId").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("AppId"));
      }
      // validate the optional field `BackendEnvironmentName`
      if (jsonObj.get("BackendEnvironmentName") != null && !jsonObj.get("BackendEnvironmentName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("BackendEnvironmentName"));
      }
      // validate the optional field `Error`
      if (jsonObj.get("Error") != null && !jsonObj.get("Error").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Error"));
      }
      // validate the optional field `ResourceConfig`
      if (jsonObj.get("ResourceConfig") != null && !jsonObj.get("ResourceConfig").isJsonNull()) {
        GetBackendAuthResponseResourceConfig.validateJsonElement(jsonObj.get("ResourceConfig"));
      }
      // validate the optional field `ResourceName`
      if (jsonObj.get("ResourceName") != null && !jsonObj.get("ResourceName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ResourceName"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetBackendAuthResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetBackendAuthResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetBackendAuthResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetBackendAuthResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetBackendAuthResponse>() {
           @Override
           public void write(JsonWriter out, GetBackendAuthResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetBackendAuthResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetBackendAuthResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetBackendAuthResponse
   * @throws IOException if the JSON string is invalid with respect to GetBackendAuthResponse
   */
  public static GetBackendAuthResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetBackendAuthResponse.class);
  }

  /**
   * Convert an instance of GetBackendAuthResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

