/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets MfaTypesElement
 */
@JsonAdapter(MfaTypesElement.Adapter.class)
public enum MfaTypesElement {
  
  SMS("SMS"),
  
  TOTP("TOTP");

  private String value;

  MfaTypesElement(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MfaTypesElement fromValue(String value) {
    for (MfaTypesElement b : MfaTypesElement.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MfaTypesElement> {
    @Override
    public void write(final JsonWriter jsonWriter, final MfaTypesElement enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MfaTypesElement read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MfaTypesElement.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    MfaTypesElement.fromValue(value);
  }
}

