/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RemoveAllBackendsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class RemoveAllBackendsRequest {
  public static final String SERIALIZED_NAME_CLEAN_AMPLIFY_APP = "cleanAmplifyApp";
  @SerializedName(SERIALIZED_NAME_CLEAN_AMPLIFY_APP)
  @javax.annotation.Nullable
  private Boolean cleanAmplifyApp;

  public RemoveAllBackendsRequest() {
  }

  public RemoveAllBackendsRequest cleanAmplifyApp(@javax.annotation.Nullable Boolean cleanAmplifyApp) {
    this.cleanAmplifyApp = cleanAmplifyApp;
    return this;
  }

  /**
   * Cleans up the Amplify Console app if this value is set to true.
   * @return cleanAmplifyApp
   */
  @javax.annotation.Nullable
  public Boolean getCleanAmplifyApp() {
    return cleanAmplifyApp;
  }

  public void setCleanAmplifyApp(@javax.annotation.Nullable Boolean cleanAmplifyApp) {
    this.cleanAmplifyApp = cleanAmplifyApp;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoveAllBackendsRequest removeAllBackendsRequest = (RemoveAllBackendsRequest) o;
    return Objects.equals(this.cleanAmplifyApp, removeAllBackendsRequest.cleanAmplifyApp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cleanAmplifyApp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoveAllBackendsRequest {\n");
    sb.append("    cleanAmplifyApp: ").append(toIndentedString(cleanAmplifyApp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cleanAmplifyApp");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RemoveAllBackendsRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RemoveAllBackendsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RemoveAllBackendsRequest is not found in the empty JSON string", RemoveAllBackendsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RemoveAllBackendsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RemoveAllBackendsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RemoveAllBackendsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RemoveAllBackendsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RemoveAllBackendsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RemoveAllBackendsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<RemoveAllBackendsRequest>() {
           @Override
           public void write(JsonWriter out, RemoveAllBackendsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RemoveAllBackendsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RemoveAllBackendsRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RemoveAllBackendsRequest
   * @throws IOException if the JSON string is invalid with respect to RemoveAllBackendsRequest
   */
  public static RemoveAllBackendsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RemoveAllBackendsRequest.class);
  }

  /**
   * Convert an instance of RemoveAllBackendsRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

