/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets UnAuthenticatedElement
 */
@JsonAdapter(UnAuthenticatedElement.Adapter.class)
public enum UnAuthenticatedElement {
  
  READ("READ"),
  
  CREATE_AND_UPDATE("CREATE_AND_UPDATE"),
  
  DELETE("DELETE");

  private String value;

  UnAuthenticatedElement(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static UnAuthenticatedElement fromValue(String value) {
    for (UnAuthenticatedElement b : UnAuthenticatedElement.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<UnAuthenticatedElement> {
    @Override
    public void write(final JsonWriter jsonWriter, final UnAuthenticatedElement enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public UnAuthenticatedElement read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return UnAuthenticatedElement.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    UnAuthenticatedElement.fromValue(value);
  }
}

