/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Describes the authorization configuration for the Amazon Cognito identity pool, provisioned as a part of your auth resource in the Amplify project.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class UpdateBackendAuthIdentityPoolConfig {
  public static final String SERIALIZED_NAME_UNAUTHENTICATED_LOGIN = "UnauthenticatedLogin";
  @SerializedName(SERIALIZED_NAME_UNAUTHENTICATED_LOGIN)
  @javax.annotation.Nullable
  private Boolean unauthenticatedLogin;

  public UpdateBackendAuthIdentityPoolConfig() {
  }

  public UpdateBackendAuthIdentityPoolConfig unauthenticatedLogin(@javax.annotation.Nullable Boolean unauthenticatedLogin) {
    this.unauthenticatedLogin = unauthenticatedLogin;
    return this;
  }

  /**
   * Get unauthenticatedLogin
   * @return unauthenticatedLogin
   */
  @javax.annotation.Nullable
  public Boolean getUnauthenticatedLogin() {
    return unauthenticatedLogin;
  }

  public void setUnauthenticatedLogin(@javax.annotation.Nullable Boolean unauthenticatedLogin) {
    this.unauthenticatedLogin = unauthenticatedLogin;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateBackendAuthIdentityPoolConfig updateBackendAuthIdentityPoolConfig = (UpdateBackendAuthIdentityPoolConfig) o;
    return Objects.equals(this.unauthenticatedLogin, updateBackendAuthIdentityPoolConfig.unauthenticatedLogin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unauthenticatedLogin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateBackendAuthIdentityPoolConfig {\n");
    sb.append("    unauthenticatedLogin: ").append(toIndentedString(unauthenticatedLogin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("UnauthenticatedLogin");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateBackendAuthIdentityPoolConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateBackendAuthIdentityPoolConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateBackendAuthIdentityPoolConfig is not found in the empty JSON string", UpdateBackendAuthIdentityPoolConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateBackendAuthIdentityPoolConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateBackendAuthIdentityPoolConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `UnauthenticatedLogin`
      if (jsonObj.get("UnauthenticatedLogin") != null && !jsonObj.get("UnauthenticatedLogin").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("UnauthenticatedLogin"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateBackendAuthIdentityPoolConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateBackendAuthIdentityPoolConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateBackendAuthIdentityPoolConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateBackendAuthIdentityPoolConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateBackendAuthIdentityPoolConfig>() {
           @Override
           public void write(JsonWriter out, UpdateBackendAuthIdentityPoolConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateBackendAuthIdentityPoolConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateBackendAuthIdentityPoolConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateBackendAuthIdentityPoolConfig
   * @throws IOException if the JSON string is invalid with respect to UpdateBackendAuthIdentityPoolConfig
   */
  public static UpdateBackendAuthIdentityPoolConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateBackendAuthIdentityPoolConfig.class);
  }

  /**
   * Convert an instance of UpdateBackendAuthIdentityPoolConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

