/*
 * AmplifyBackend
 * AWS Amplify Admin API
 *
 * The version of the OpenAPI document: 2020-08-11
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CreateBackendAuthForgotPasswordConfigEmailSettings;
import org.openapitools.client.model.DeliveryMethod;
import org.openapitools.client.model.UpdateBackendAuthForgotPasswordConfigSmsSettings;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * &lt;b&gt;(DEPRECATED)&lt;/b&gt; Describes the forgot password policy for authenticating into the Amplify app.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:09:35.840549+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class UpdateBackendAuthForgotPasswordConfig {
  public static final String SERIALIZED_NAME_DELIVERY_METHOD = "DeliveryMethod";
  @SerializedName(SERIALIZED_NAME_DELIVERY_METHOD)
  @javax.annotation.Nullable
  private DeliveryMethod deliveryMethod;

  public static final String SERIALIZED_NAME_EMAIL_SETTINGS = "EmailSettings";
  @SerializedName(SERIALIZED_NAME_EMAIL_SETTINGS)
  @javax.annotation.Nullable
  private CreateBackendAuthForgotPasswordConfigEmailSettings emailSettings;

  public static final String SERIALIZED_NAME_SMS_SETTINGS = "SmsSettings";
  @SerializedName(SERIALIZED_NAME_SMS_SETTINGS)
  @javax.annotation.Nullable
  private UpdateBackendAuthForgotPasswordConfigSmsSettings smsSettings;

  public UpdateBackendAuthForgotPasswordConfig() {
  }

  public UpdateBackendAuthForgotPasswordConfig deliveryMethod(@javax.annotation.Nullable DeliveryMethod deliveryMethod) {
    this.deliveryMethod = deliveryMethod;
    return this;
  }

  /**
   * Get deliveryMethod
   * @return deliveryMethod
   */
  @javax.annotation.Nullable
  public DeliveryMethod getDeliveryMethod() {
    return deliveryMethod;
  }

  public void setDeliveryMethod(@javax.annotation.Nullable DeliveryMethod deliveryMethod) {
    this.deliveryMethod = deliveryMethod;
  }


  public UpdateBackendAuthForgotPasswordConfig emailSettings(@javax.annotation.Nullable CreateBackendAuthForgotPasswordConfigEmailSettings emailSettings) {
    this.emailSettings = emailSettings;
    return this;
  }

  /**
   * Get emailSettings
   * @return emailSettings
   */
  @javax.annotation.Nullable
  public CreateBackendAuthForgotPasswordConfigEmailSettings getEmailSettings() {
    return emailSettings;
  }

  public void setEmailSettings(@javax.annotation.Nullable CreateBackendAuthForgotPasswordConfigEmailSettings emailSettings) {
    this.emailSettings = emailSettings;
  }


  public UpdateBackendAuthForgotPasswordConfig smsSettings(@javax.annotation.Nullable UpdateBackendAuthForgotPasswordConfigSmsSettings smsSettings) {
    this.smsSettings = smsSettings;
    return this;
  }

  /**
   * Get smsSettings
   * @return smsSettings
   */
  @javax.annotation.Nullable
  public UpdateBackendAuthForgotPasswordConfigSmsSettings getSmsSettings() {
    return smsSettings;
  }

  public void setSmsSettings(@javax.annotation.Nullable UpdateBackendAuthForgotPasswordConfigSmsSettings smsSettings) {
    this.smsSettings = smsSettings;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateBackendAuthForgotPasswordConfig updateBackendAuthForgotPasswordConfig = (UpdateBackendAuthForgotPasswordConfig) o;
    return Objects.equals(this.deliveryMethod, updateBackendAuthForgotPasswordConfig.deliveryMethod) &&
        Objects.equals(this.emailSettings, updateBackendAuthForgotPasswordConfig.emailSettings) &&
        Objects.equals(this.smsSettings, updateBackendAuthForgotPasswordConfig.smsSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryMethod, emailSettings, smsSettings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateBackendAuthForgotPasswordConfig {\n");
    sb.append("    deliveryMethod: ").append(toIndentedString(deliveryMethod)).append("\n");
    sb.append("    emailSettings: ").append(toIndentedString(emailSettings)).append("\n");
    sb.append("    smsSettings: ").append(toIndentedString(smsSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("DeliveryMethod");
    openapiFields.add("EmailSettings");
    openapiFields.add("SmsSettings");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateBackendAuthForgotPasswordConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateBackendAuthForgotPasswordConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateBackendAuthForgotPasswordConfig is not found in the empty JSON string", UpdateBackendAuthForgotPasswordConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateBackendAuthForgotPasswordConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateBackendAuthForgotPasswordConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `DeliveryMethod`
      if (jsonObj.get("DeliveryMethod") != null && !jsonObj.get("DeliveryMethod").isJsonNull()) {
        DeliveryMethod.validateJsonElement(jsonObj.get("DeliveryMethod"));
      }
      // validate the optional field `EmailSettings`
      if (jsonObj.get("EmailSettings") != null && !jsonObj.get("EmailSettings").isJsonNull()) {
        CreateBackendAuthForgotPasswordConfigEmailSettings.validateJsonElement(jsonObj.get("EmailSettings"));
      }
      // validate the optional field `SmsSettings`
      if (jsonObj.get("SmsSettings") != null && !jsonObj.get("SmsSettings").isJsonNull()) {
        UpdateBackendAuthForgotPasswordConfigSmsSettings.validateJsonElement(jsonObj.get("SmsSettings"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateBackendAuthForgotPasswordConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateBackendAuthForgotPasswordConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateBackendAuthForgotPasswordConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateBackendAuthForgotPasswordConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateBackendAuthForgotPasswordConfig>() {
           @Override
           public void write(JsonWriter out, UpdateBackendAuthForgotPasswordConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateBackendAuthForgotPasswordConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateBackendAuthForgotPasswordConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateBackendAuthForgotPasswordConfig
   * @throws IOException if the JSON string is invalid with respect to UpdateBackendAuthForgotPasswordConfig
   */
  public static UpdateBackendAuthForgotPasswordConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateBackendAuthForgotPasswordConfig.class);
  }

  /**
   * Convert an instance of UpdateBackendAuthForgotPasswordConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

